// flow-typed signature: 6abdda3fa28b2ac2ea4a1df620560340
// flow-typed version: <<STUB>>/jq_v^1.7.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jq/dist/jquery' {
  declare module.exports: any;
}

declare module 'jq/lib/jq' {
  declare module.exports: any;
}

declare module 'jq/lib/jquery.prefix' {
  declare module.exports: any;
}

declare module 'jq/lib/jquery.suffix' {
  declare module.exports: any;
}

declare module 'jq/test/jquery.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jq/dist/jquery.js' {
  declare module.exports: $Exports<'jq/dist/jquery'>;
}
declare module 'jq/index' {
  declare module.exports: $Exports<'jq'>;
}
declare module 'jq/index.js' {
  declare module.exports: $Exports<'jq'>;
}
declare module 'jq/lib/jq.js' {
  declare module.exports: $Exports<'jq/lib/jq'>;
}
declare module 'jq/lib/jquery.prefix.js' {
  declare module.exports: $Exports<'jq/lib/jquery.prefix'>;
}
declare module 'jq/lib/jquery.suffix.js' {
  declare module.exports: $Exports<'jq/lib/jquery.suffix'>;
}
declare module 'jq/test/jquery.test.js' {
  declare module.exports: $Exports<'jq/test/jquery.test'>;
}
