// flow-typed signature: 8c19a4d8d5fb7bd6e31720219caa9505
// flow-typed version: <<STUB>>/package.json_v^2.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package.json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'package.json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'package.json/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'package.json/lib/index.js' {
  declare module.exports: $Exports<'package.json/lib/index'>;
}
