// flow-typed signature: a12a58d9e6f4e01eb21d012760bdd745
// flow-typed version: <<STUB>>/@babel/types_v7.0.0-beta.40/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/types/lib/asserts/assertNode' {
  declare module.exports: any;
}

declare module '@babel/types/lib/asserts/generated/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/builders/builder' {
  declare module.exports: any;
}

declare module '@babel/types/lib/builders/flow/createTypeAnnotationBasedOnTypeof' {
  declare module.exports: any;
}

declare module '@babel/types/lib/builders/flow/createUnionTypeAnnotation' {
  declare module.exports: any;
}

declare module '@babel/types/lib/builders/generated/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/builders/react/buildChildren' {
  declare module.exports: any;
}

declare module '@babel/types/lib/clone/clone' {
  declare module.exports: any;
}

declare module '@babel/types/lib/clone/cloneDeep' {
  declare module.exports: any;
}

declare module '@babel/types/lib/clone/cloneNode' {
  declare module.exports: any;
}

declare module '@babel/types/lib/clone/cloneWithoutLoc' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/addComment' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/addComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/inheritInnerComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/inheritLeadingComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/inheritsComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/inheritTrailingComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/comments/removeComments' {
  declare module.exports: any;
}

declare module '@babel/types/lib/constants/generated/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/constants/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/ensureBlock' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/gatherSequenceExpressions' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toBindingIdentifierName' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toBlock' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toComputedKey' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toExpression' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toIdentifier' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toKeyAlias' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toSequenceExpression' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/toStatement' {
  declare module.exports: any;
}

declare module '@babel/types/lib/converters/valueToNode' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/core' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/es2015' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/experimental' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/flow' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/jsx' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/misc' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/typescript' {
  declare module.exports: any;
}

declare module '@babel/types/lib/definitions/utils' {
  declare module.exports: any;
}

declare module '@babel/types/lib/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/appendToMemberExpression' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/flow/removeTypeDuplicates' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/inherits' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/prependToMemberExpression' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/removeProperties' {
  declare module.exports: any;
}

declare module '@babel/types/lib/modifications/removePropertiesDeep' {
  declare module.exports: any;
}

declare module '@babel/types/lib/retrievers/getBindingIdentifiers' {
  declare module.exports: any;
}

declare module '@babel/types/lib/retrievers/getOuterBindingIdentifiers' {
  declare module.exports: any;
}

declare module '@babel/types/lib/traverse/traverse' {
  declare module.exports: any;
}

declare module '@babel/types/lib/traverse/traverseFast' {
  declare module.exports: any;
}

declare module '@babel/types/lib/utils/inherit' {
  declare module.exports: any;
}

declare module '@babel/types/lib/utils/react/cleanJSXElementLiteralChild' {
  declare module.exports: any;
}

declare module '@babel/types/lib/utils/shallowEqual' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/buildMatchMemberExpression' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/generated/index' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/is' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isBinding' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isBlockScoped' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isImmutable' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isLet' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isNode' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isNodesEquivalent' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isReferenced' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isScope' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isSpecifierDefault' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isType' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isValidES3Identifier' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isValidIdentifier' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/isVar' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/matchesPattern' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/react/isCompatTag' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/react/isReactComponent' {
  declare module.exports: any;
}

declare module '@babel/types/lib/validators/validate' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/generateTypeHelpers' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/generators/generateAsserts' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/generators/generateBuilders' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/generators/generateConstants' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/generators/generateValidators' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/utils/formatBuilderName' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/utils/formatCode' {
  declare module.exports: any;
}

declare module '@babel/types/scripts/utils/lowerFirst' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/types/lib/asserts/assertNode.js' {
  declare module.exports: $Exports<'@babel/types/lib/asserts/assertNode'>;
}
declare module '@babel/types/lib/asserts/generated/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/asserts/generated/index'>;
}
declare module '@babel/types/lib/builders/builder.js' {
  declare module.exports: $Exports<'@babel/types/lib/builders/builder'>;
}
declare module '@babel/types/lib/builders/flow/createTypeAnnotationBasedOnTypeof.js' {
  declare module.exports: $Exports<'@babel/types/lib/builders/flow/createTypeAnnotationBasedOnTypeof'>;
}
declare module '@babel/types/lib/builders/flow/createUnionTypeAnnotation.js' {
  declare module.exports: $Exports<'@babel/types/lib/builders/flow/createUnionTypeAnnotation'>;
}
declare module '@babel/types/lib/builders/generated/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/builders/generated/index'>;
}
declare module '@babel/types/lib/builders/react/buildChildren.js' {
  declare module.exports: $Exports<'@babel/types/lib/builders/react/buildChildren'>;
}
declare module '@babel/types/lib/clone/clone.js' {
  declare module.exports: $Exports<'@babel/types/lib/clone/clone'>;
}
declare module '@babel/types/lib/clone/cloneDeep.js' {
  declare module.exports: $Exports<'@babel/types/lib/clone/cloneDeep'>;
}
declare module '@babel/types/lib/clone/cloneNode.js' {
  declare module.exports: $Exports<'@babel/types/lib/clone/cloneNode'>;
}
declare module '@babel/types/lib/clone/cloneWithoutLoc.js' {
  declare module.exports: $Exports<'@babel/types/lib/clone/cloneWithoutLoc'>;
}
declare module '@babel/types/lib/comments/addComment.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/addComment'>;
}
declare module '@babel/types/lib/comments/addComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/addComments'>;
}
declare module '@babel/types/lib/comments/inheritInnerComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/inheritInnerComments'>;
}
declare module '@babel/types/lib/comments/inheritLeadingComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/inheritLeadingComments'>;
}
declare module '@babel/types/lib/comments/inheritsComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/inheritsComments'>;
}
declare module '@babel/types/lib/comments/inheritTrailingComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/inheritTrailingComments'>;
}
declare module '@babel/types/lib/comments/removeComments.js' {
  declare module.exports: $Exports<'@babel/types/lib/comments/removeComments'>;
}
declare module '@babel/types/lib/constants/generated/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/constants/generated/index'>;
}
declare module '@babel/types/lib/constants/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/constants/index'>;
}
declare module '@babel/types/lib/converters/ensureBlock.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/ensureBlock'>;
}
declare module '@babel/types/lib/converters/gatherSequenceExpressions.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/gatherSequenceExpressions'>;
}
declare module '@babel/types/lib/converters/toBindingIdentifierName.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toBindingIdentifierName'>;
}
declare module '@babel/types/lib/converters/toBlock.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toBlock'>;
}
declare module '@babel/types/lib/converters/toComputedKey.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toComputedKey'>;
}
declare module '@babel/types/lib/converters/toExpression.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toExpression'>;
}
declare module '@babel/types/lib/converters/toIdentifier.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toIdentifier'>;
}
declare module '@babel/types/lib/converters/toKeyAlias.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toKeyAlias'>;
}
declare module '@babel/types/lib/converters/toSequenceExpression.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toSequenceExpression'>;
}
declare module '@babel/types/lib/converters/toStatement.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/toStatement'>;
}
declare module '@babel/types/lib/converters/valueToNode.js' {
  declare module.exports: $Exports<'@babel/types/lib/converters/valueToNode'>;
}
declare module '@babel/types/lib/definitions/core.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/core'>;
}
declare module '@babel/types/lib/definitions/es2015.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/es2015'>;
}
declare module '@babel/types/lib/definitions/experimental.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/experimental'>;
}
declare module '@babel/types/lib/definitions/flow.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/flow'>;
}
declare module '@babel/types/lib/definitions/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/index'>;
}
declare module '@babel/types/lib/definitions/jsx.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/jsx'>;
}
declare module '@babel/types/lib/definitions/misc.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/misc'>;
}
declare module '@babel/types/lib/definitions/typescript.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/typescript'>;
}
declare module '@babel/types/lib/definitions/utils.js' {
  declare module.exports: $Exports<'@babel/types/lib/definitions/utils'>;
}
declare module '@babel/types/lib/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/index'>;
}
declare module '@babel/types/lib/modifications/appendToMemberExpression.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/appendToMemberExpression'>;
}
declare module '@babel/types/lib/modifications/flow/removeTypeDuplicates.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/flow/removeTypeDuplicates'>;
}
declare module '@babel/types/lib/modifications/inherits.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/inherits'>;
}
declare module '@babel/types/lib/modifications/prependToMemberExpression.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/prependToMemberExpression'>;
}
declare module '@babel/types/lib/modifications/removeProperties.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/removeProperties'>;
}
declare module '@babel/types/lib/modifications/removePropertiesDeep.js' {
  declare module.exports: $Exports<'@babel/types/lib/modifications/removePropertiesDeep'>;
}
declare module '@babel/types/lib/retrievers/getBindingIdentifiers.js' {
  declare module.exports: $Exports<'@babel/types/lib/retrievers/getBindingIdentifiers'>;
}
declare module '@babel/types/lib/retrievers/getOuterBindingIdentifiers.js' {
  declare module.exports: $Exports<'@babel/types/lib/retrievers/getOuterBindingIdentifiers'>;
}
declare module '@babel/types/lib/traverse/traverse.js' {
  declare module.exports: $Exports<'@babel/types/lib/traverse/traverse'>;
}
declare module '@babel/types/lib/traverse/traverseFast.js' {
  declare module.exports: $Exports<'@babel/types/lib/traverse/traverseFast'>;
}
declare module '@babel/types/lib/utils/inherit.js' {
  declare module.exports: $Exports<'@babel/types/lib/utils/inherit'>;
}
declare module '@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js' {
  declare module.exports: $Exports<'@babel/types/lib/utils/react/cleanJSXElementLiteralChild'>;
}
declare module '@babel/types/lib/utils/shallowEqual.js' {
  declare module.exports: $Exports<'@babel/types/lib/utils/shallowEqual'>;
}
declare module '@babel/types/lib/validators/buildMatchMemberExpression.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/buildMatchMemberExpression'>;
}
declare module '@babel/types/lib/validators/generated/index.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/generated/index'>;
}
declare module '@babel/types/lib/validators/is.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/is'>;
}
declare module '@babel/types/lib/validators/isBinding.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isBinding'>;
}
declare module '@babel/types/lib/validators/isBlockScoped.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isBlockScoped'>;
}
declare module '@babel/types/lib/validators/isImmutable.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isImmutable'>;
}
declare module '@babel/types/lib/validators/isLet.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isLet'>;
}
declare module '@babel/types/lib/validators/isNode.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isNode'>;
}
declare module '@babel/types/lib/validators/isNodesEquivalent.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isNodesEquivalent'>;
}
declare module '@babel/types/lib/validators/isReferenced.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isReferenced'>;
}
declare module '@babel/types/lib/validators/isScope.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isScope'>;
}
declare module '@babel/types/lib/validators/isSpecifierDefault.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isSpecifierDefault'>;
}
declare module '@babel/types/lib/validators/isType.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isType'>;
}
declare module '@babel/types/lib/validators/isValidES3Identifier.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isValidES3Identifier'>;
}
declare module '@babel/types/lib/validators/isValidIdentifier.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isValidIdentifier'>;
}
declare module '@babel/types/lib/validators/isVar.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/isVar'>;
}
declare module '@babel/types/lib/validators/matchesPattern.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/matchesPattern'>;
}
declare module '@babel/types/lib/validators/react/isCompatTag.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/react/isCompatTag'>;
}
declare module '@babel/types/lib/validators/react/isReactComponent.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/react/isReactComponent'>;
}
declare module '@babel/types/lib/validators/validate.js' {
  declare module.exports: $Exports<'@babel/types/lib/validators/validate'>;
}
declare module '@babel/types/scripts/generateTypeHelpers.js' {
  declare module.exports: $Exports<'@babel/types/scripts/generateTypeHelpers'>;
}
declare module '@babel/types/scripts/generators/generateAsserts.js' {
  declare module.exports: $Exports<'@babel/types/scripts/generators/generateAsserts'>;
}
declare module '@babel/types/scripts/generators/generateBuilders.js' {
  declare module.exports: $Exports<'@babel/types/scripts/generators/generateBuilders'>;
}
declare module '@babel/types/scripts/generators/generateConstants.js' {
  declare module.exports: $Exports<'@babel/types/scripts/generators/generateConstants'>;
}
declare module '@babel/types/scripts/generators/generateValidators.js' {
  declare module.exports: $Exports<'@babel/types/scripts/generators/generateValidators'>;
}
declare module '@babel/types/scripts/utils/formatBuilderName.js' {
  declare module.exports: $Exports<'@babel/types/scripts/utils/formatBuilderName'>;
}
declare module '@babel/types/scripts/utils/formatCode.js' {
  declare module.exports: $Exports<'@babel/types/scripts/utils/formatCode'>;
}
declare module '@babel/types/scripts/utils/lowerFirst.js' {
  declare module.exports: $Exports<'@babel/types/scripts/utils/lowerFirst'>;
}
