// flow-typed signature: caa8345d949cd459ecb81951f2d0f9bc
// flow-typed version: <<STUB>>/@morlay/eslint-config_v3.0.x/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@morlay/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@morlay/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@morlay/eslint-config/index' {
  declare module.exports: $Exports<'@morlay/eslint-config'>;
}
declare module '@morlay/eslint-config/index.js' {
  declare module.exports: $Exports<'@morlay/eslint-config'>;
}
